### ISSUE TITLE
Fix Bluetooth

### ISSUE THREAD

**Issue by daviddean-x** [zspherez/Dell-XPS-9500-4K-UHD-Monterey#1]
You should not use injectbluetooth kext

Notes from itwlm: 

What additional steps should I do to make Bluetooth work on macOS Monterey
Make sure IntelBluetoothFirmware.kext v1.1.3 or newer is used.
Exclude the injection of IntelBluetoothInjector.kext for macOS Monterey from the Bootloader's config
Include BlueToolFixup.kext from acidanthera/BrcmPatchRAM(opens new window)

**Comment by zspherez** [comment]
InjectBluetooth kext is disabled in config.plist, as is stated in itlwm documentation. Bluetooth is working in current configuration aside from AirDrop, which is not an expected functionality and is likely because of the Intel wifi card rather than the bluetooth side of things.

**Comment by zspherez** [comment]
closed based off newest commit
