### ISSUE TITLE
power status bug

### ISSUE THREAD

**Issue by sweet3c** [zspherez/Dell-XPS-9500-4K-UHD-Monterey#2]
把电源拔掉后，系统还现实充电状态，并且在接下来的使用中也不会更新电源状态，直到电池耗尽后，电脑自动关机

**Comment by zspherez** [comment]
Could you provide some more information on this bug? I have not noticed this to be an issue but I'm not sure if it translated correctly? @sweet3c

**Comment by sweet3c** [comment]
> Could you provide some more information on this bug? I have not noticed this to be an issue but I'm not sure if it translated correctly? @sweet3c

The battery's status can't update when:

the adapter from on to off or from off to on
when the adapter is off the battery's value stop at 100%, and then use the laptop with battery, the laptop will auto shutdown when the battery is exhausted.

situation 1(adapter from on -> off): charge the battery to 100%  and keep the adapter on. turn on the laptop and login the OS, you can see the battery's status is charging with 100%, then take away the adapter  you can see the battery's status is still with charging with 100%. Then use the laptop some time  you can see the battery's status also still with charging with 100% ,the battery's status can not be updated  

situation 1(adapter from off -> on):  some times ,for example  the battery's status is not charging ,value is not 100% ,then take the adapter in to laptop, the battery's status can't be updated to charging 

This laptop at present  have 4 problems
1. The above bug battery's status
2. S3 sleep : I have reported to Dell's Official, hope they can update the BIOS to support S3 sleep
3. Headphone jack 
4. This laptop have 4 speakers, at present the AppleALC's  layout-id can only make two of them work

**Comment by zspherez** [comment]
@sweet3c I now understand what you are saying, but I have not run into this issue. My battery status in my taskbar behaves as is expected. When I plug it in, the status updates to charging, and when it is fully charged and I unplug it, it updates to not charging. Could you maybe provide a video of what you are seeing? 

As for the other issues, some are already updated in the readme, I will update to add the rest. However, I see that you have a forked version of AppleALC that you added support for this machine. Does this fix the speakers and headphone jack issues that you mentioned?

**Comment by zspherez** [comment]
Closing because my machine is not running into this problem with the EFI from this repo.
