### ISSUE TITLE
Internal Display not working when connected to HDMI

### ISSUE THREAD

**Issue by rkzed94** [zspherez/Dell-XPS-9500-4K-UHD-Monterey#3]
hello, i was able to connect external monitor through HDMI but the main internal display turns black as soon as the HDMI connected.
it still detected in the display list just not though, just not displaying any images.
also when i disconnect the HDMI, the main display wont come back until i restart my laptop..

**Comment by zspherez** [comment]
@rkzed94 Which display do you have? This repo is specifically for the XPS 9500 with the 4K display.

**Comment by rkzed94** [comment]
@zspherez, thankyou for your reply.
its 1080 one.

**Comment by rkzed94** [comment]
i also tried using zachs78's config.plist for PciRoot(0x0)/Pci(0x2,0x0) value but it also did not work.
have you tried to connect yours to external monitor using HDMI?

**Comment by zspherez** [comment]
@rkzed94 I use a monitor using HDMI on a daily basis and it works fine for me. It is likely something in that offset, they are going to be different because the graphics are handled differently on the computer with the 1080 display.

Closed due to mismatched devices
