### ISSUE TITLE
卡在detected nested debugger entry count exceeding 5

### ISSUE THREAD

**Issue by yanshuzong** [zspherez/Dell-XPS-9500-4K-UHD-Monterey#4]
卡在detected nested debugger entry count exceeding 5

**Comment by zspherez** [comment]
Please explain what you mean by this...

**Comment by zspherez** [comment]
@yanshuzong please explain what you mean by this

**Comment by yanshuzong** [comment]
![微信图片_20220307120444](https://user-images.githubusercontent.com/54058075/156966202-f6325fb7-2782-4eec-8c1b-4c9510a9183e.jpg)
引导时卡在这个界面~

**Comment by yanshuzong** [comment]
> @yanshuzong please explain what you mean by this
![微信图片_20220307120444](https://user-images.githubusercontent.com/54058075/156966366-089c501a-4bb2-4797-b8eb-c3dc501715b4.jpg)
引导时卡在这个界面

**Comment by zspherez** [comment]
This does not happen on my machine, make sure that you set up your EFI correctly.
