### ISSUE TITLE
type c to second monitor (TYPE C 转外接显示器)

### ISSUE THREAD

**Issue by flyinghappyking** [zspherez/Dell-XPS-9500-4K-UHD-Monterey#5]
请问,可以通过TYPE　C　转外接显示器吗?　转什么接口的,谢谢了.

**Comment by zspherez** [comment]
type C to second monitor works with no changes, simply plug in the monitor

**Comment by flyinghappyking** [comment]
type C to HDMI or DP, and you have tried it, right?
thank you for your reply and your work, it is appreciated!

**Comment by zspherez** [comment]
I have used both, I use type C to DP daily, but have confirmed type C to HDMI works as well.
